version: "3.3"

services:
  app:
    build: .
    command: bash start.sh
    restart: on-failure
    ports:
      - "125:125"
      - "5202:5202"
networks:
  default:
    external: true
    name: network11